export const ProductItems = [
    {
      "id": 1,
      "productName": "Apple iPhone 14",
      "marketPrice": 999,
      "sellingPrice": 949,
      "numberOfProducts": 10,
      "Available": true,
    },
    {
      "id": 2,
      "productName": "Samsung Galaxy S23",
      "marketPrice": 899,
      "sellingPrice": 849,
      "numberOfProducts": 15,
      "Available": true,
    },
    {
      "id": 3,
      "productName": "Sony WH-1000XM5 Headphones",
      "marketPrice": 399,
      "sellingPrice": 349,
      "numberOfProducts": 0,
      "Available": false,
    },
    {
      "id": 4,
      "productName": "Dell XPS 13 Laptop",
      "marketPrice": 1199,
      "sellingPrice": 1099,
      "numberOfProducts": 5,
      "Available": true,
    },
    {
      "id": 5,
      "productName": "Nike Air Max 270",
      "marketPrice": 150,
      "sellingPrice": 120,
      "numberOfProducts": 30,
      "Available": true,
    },
    {
      "id": 6,
      "productName": "Logitech MX Master 3 Mouse",
      "marketPrice": 99,
      "sellingPrice": 89,
      "numberOfProducts": 0,
      "Available": false,
    },
    {
      "id": 7,
      "productName": "Amazon Echo Dot (5th Gen)",
      "marketPrice": 50,
      "sellingPrice": 44,
      "numberOfProducts": 40,
      "Available": true,
    },
    {
      "id": 8,
      "productName": "Bose SoundLink Revolve+",
      "marketPrice": 299,
      "sellingPrice": 259,
      "numberOfProducts": 0,
      "Available": false,
    },
    {
      "id": 9,
      "productName": "HP Envy 13 Laptop",
      "marketPrice": 999,
      "sellingPrice": 899,
      "numberOfProducts": 8,
      "Available": true,
    },
    {
      "id": 10,
      "productName": "Adidas Ultraboost 22",
      "marketPrice": 180,
      "sellingPrice": 150,
      "numberOfProducts": 35,
      "Available": true,
    }
  ]
